#pragma once

#ifndef _CONSTS_

	#define ID_CONTEXT_NOTHING 					WM_USER +   1
	#define ID_CONTEXT_UPDATECATALOG			WM_USER + 101
	#define ID_CONTEXT_UPDATEPLAYLIST			WM_USER + 102
	#define ID_CONTEXT_UPDATEARTIST 			WM_USER + 103
	#define ID_CONTEXT_SEARCHDIALOG 			WM_USER + 104
	#define ID_CONTEXT_RELOADCACHE	 			WM_USER + 105

	#define ID_CONTEXT_UPDATECATALOG_DONE       WM_USER  + 201
	#define ID_CONTEXT_UPDATEPLAYLIST_DONE      WM_USER  + 202
	#define ID_CONTEXT_UPDATEARTIST_DONE        WM_USER  + 203

	#define ID_SEARCH_DONE						WM_USER  + 301

	#define ID_CLEAR_LIST						WM_USER  + 401

	#define IDC_TREEVIEWCTRL					2053

	#define TREE_ROOT_CATALOG					0
	#define TREE_ROOT_PLAYLISTS					1

#define _CONSTS_
#endif